version: '3.0'
services:
    meilisearch:
        image: getmeili/meilisearch:v1.5
        ports:
            - '7700:7700'
        volumes:
            - ./data.ms:/data.ms
        environment:
            - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}

